{
 "title": "Lab Reservas Académicas",
 "panels": [
  {
   "title": "API UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"reservas\",instance=\"10.10.0.20:8080\"}"
    }
   ]
  },
  {
   "title": "Core UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"reservas\",instance=\"10.10.0.30:8080\"}"
    }
   ]
  },
  {
   "title": "CPU nodos lab",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)"
    }
   ]
  },
  {
   "title": "Reservas totales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "lab_reservations_total" }
   ]
  }
 ]
}